FROM golang:alpine

RUN apk add --no-cache ca-certificates git

WORKDIR /go/src/github.com/tilegame/gameserver

COPY . .

RUN go get -d -v ./...
RUN go install -v ./...

# application requires both ports to be open.
EXPOSE 443
EXPOSE 80

# cache for certificates generated by golang.org/x/crypto/acme/autocert
VOLUME ["/certs"]

CMD ["gameserver", "-a", ":80", "tls"]


# note:
# look at this for making a better docker file.
# https://brendanr.net/blog/go-docker-https/
